packageExtensions:
  "@babel/parser@*":
    dependencies:
      "@babel/types": "*"
  "@vue/cli-plugin-typescript@*":
    dependencies:
      babel-loader: "*"
  "@vue/cli-service@*":
    peerDependencies:
      "@vue/cli-plugin-babel": "*"
      "@vue/cli-plugin-eslint": "*"
      "@vue/cli-plugin-typescript": "*"
  babel-loader@*:
    dependencies:
      "@babel/core": "*"
  debug@*:
    dependencies:
      supports-color: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      vue-template-compiler: "*"
    peerDependencies:
      typescript: "*"
  promise-inflight@*:
    dependencies:
      bluebird: "*"
  vue-jest@*:
    dependencies:
      source-map: "*"
      vue-template-compiler: "*"
  vue-loader@*:
    dependencies:
      webpack: "*"
  vue-router@*:
    dependencies:
      vue: "*"
  vuex@*:
    dependencies:
      vue: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-constraints.cjs
    spec: "@yarnpkg/plugin-constraints"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpMode: strict

yarnPath: .yarn/releases/yarn-2.2.2.cjs
